#!/usr/bin/env node
'use strict';

const { promises: fs } = require("fs");
const path = require("path");

async function copyDir(src, dest) {
    await fs.mkdir(dest, { recursive: true });
    let entries = await fs.readdir(src, { withFileTypes: true });

    for (let entry of entries) {
        let srcPath = path.join(src, entry.name);
        let destPath = path.join(dest, entry.name);

        entry.isDirectory()
            ? await copyDir(srcPath, destPath)
            : await fs.copyFile(srcPath, destPath);
    }
};

copyDir(
	path.join(__dirname, '../node_modules/@scottish-government/design-system/dist'),
	path.join(__dirname, '../public/design-system/'),
);

copyDir(
	path.join(__dirname, '../node_modules/@scottish-government/design-system/src/images/documents/svg'),
	path.join(__dirname, '../public/images/documents/'),
);
